<a href="https://colab.research.google.com/github/BadaraiahGuntapalli/Machine-Learning/blob/main/sample_File_to_save_to_github.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
x = np.random.randint(10, high=50, size = (2, 5))

In [4]:
print(x)

[[17 10 15 22 33]
 [47 39 10 31 43]]


In [6]:
y = 5 + x**2

In [7]:
print(y)

[[ 294  105  230  489 1094]
 [2214 1526  105  966 1854]]
